import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>coding hunter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
        coding hunter
        </h1>

        <p className={styles.description}>
         A blog for coding hunters by coding hunters
        </p>
        <div className="blogs">
          <h2>Popular blogs</h2>
      <div className="blogItems">
        <h3>How to learn javascript in 2022?</h3>
        <p>Javascript is the language used to design logic for the web</p>
      </div>
      </div>
      </main>

     
    </div>
  )
}
